#!/bin/bash

source ~/.nvm/nvm.sh
nvm install 4.2

sudo apt-get update
sudo apt-get install libkrb5-dev

npm install body-parser --save
npm install express --save
npm install lodash --save
npm install mongodb --save
npm install yargs --save

npm install babel --save-dev
npm install chai --save-dev
npm install chai-as-promised --save-dev
npm install del --save-dev
npm install gulp --save-dev
npm install gulp-babel --save-dev
npm install gulp-eslint --save-dev
npm install gulp-mocha --save-dev
npm install gulp-nodemon --save-dev
npm install supertest --save-dev
npm install supertest-as-promised --save-dev
